FuliangMart/FuliangMart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("martApp.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    # this is for ckeditor app for customize web text(like product: title, descriptions etc) editor
    path("ckeditor/", include("ckeditor_uploader.urls"))

    # paypal integrations
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

FuliangMart/martApp/urls.py
from django.urls import path, include
from martApp.views import index, checkout, ajax_contact, contact, remove_wishlist, add_to_wishlist, wishlist_view, make_address_default, order_success, order_detail, customer_dashboard,  update_cart, delete_item_from_cart, cart_view, add_to_cart, search_view, filter_product, product_list_view, ajax_add_review, tag_list, categories_list, category_product_list_view, vendor_list_view, vendor_detail_view, product_detail_view
from martApp import views

app_name = "martApp"

urlpatterns = [
    path("", index, name="index"),
    path("products/", product_list_view, name="product_list"),

    path("product/<pid>/", product_detail_view, name="product_detail"),
    path("category/", categories_list, name="categories"),

    path("category/<cid>/", category_product_list_view, name="category-product-list"),
    path("vendor/", vendor_list_view, name="vendor_list"),
    
    path("vendors/<vid>/", vendor_detail_view, name="vendor_detail"),
    path("tag/<slug:tag_slug>/", tag_list, name="tag_list"),
    # add review
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),
    
    path("search/", search_view, name="search"),
    # product filter
    path("filter-products/", filter_product, name="filter-product"),
    # add to cart link
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),

    path("update-cart/", update_cart, name="update-cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),


    path("wishlist/", wishlist_view, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),

    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),

    # path("checkout/<str:oid>/", checkout, name="checkout"),
    path("checkout/<oid>", checkout, name="checkout"),
    

    path('order-success/', order_success, name="order_success"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),

    path("dashboard/", customer_dashboard, name="dashboard"),
    path("contact/", contact, name="contact"),

    path("ajax-contact-form/", ajax_contact, name="ajax-contact-form"),

    # making address default
    path('make-default-address/', make_address_default, name="make-address-default"),
    
    
    # new path
    path('save-checkout-info/', views.save_checkout_info, name="save_checkout_info"),
    
    path('privacy_policy/', views.privacy_policy, name="privacy_policy"),
    path('purchase_guide/', views.purchase_guide, name="purchase_guide"),
    path('terms_of_service/', views.terms_of_service, name="terms_of_service"),
    path('about_us/', views.about_us, name="about_us"),
    
]

FuliangMart/useradmin/urls.py
from django.urls import path
from useradmin import views

app_name = "useradmin"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("products", views.products, name="products"),
    path("add_product", views.add_product, name="add_product"),
    path("edit_product<pid>", views.edit_product, name="edit_product"),
    path("delete_products<pid>", views.delete_products, name="delete_products"),
    path("orders", views.orders, name="orders"),
    path("order_detail/<oid>/", views.order_detail, name="order_detail"),
    path("change_order_status<oid>/", views.change_order_status, name="change_order_status"),
    path("shop_page/<str:vid>/", views.shop_page, name="shop_page"),
    path("reviews", views.reviews, name="reviews"),
    path("settings", views.settings, name="settings"),
    path("change_password", views.change_password, name="change_password"),
]

FuliangMart/martApp/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField #pip install shortuuid
from django.utils.html import mark_safe 
from userauths.models import User
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


STATUS_CHOICE = {
    ("process", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
}

STATUS = {
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In Review"),
    ("published", "Published"),
}

RATINGS = {
    (1, "⭐☆☆☆☆"),
    (2, "⭐⭐★☆☆"),
    (3, "⭐⭐⭐★☆"),
    (4, "⭐⭐⭐⭐☆"),
    (5, "⭐⭐⭐⭐⭐"),
}


def user_directroy_path(instance, filename):
    return "user_{0}/{1}".format(instance.user.id, filename)

# Create your models here.
class Category(models.Model):
    cid = ShortUUIDField(unique = True, length = 10, max_length = 30, prefix = "cat", alphabet = "abcdefgh12345")
    title = models.CharField(max_length = 100, default = "Grocery")
    image = models.ImageField(upload_to="category")

    class Meta:
        verbose_name_plural = "Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width = "50" height = "50" />' % (self.image.url))
    
    def __str__(self):
        return self.title
    
class Tags(models.Model):
    # tags = TaggableManager(blank=True)
    pass
    # TO USE tags i have to install (>> pip install django-taggit)

class Vendor(models.Model):
    vid = ShortUUIDField(unique = True, length = 10, max_length = 30, prefix = "ven", alphabet = "abcdefgh12345")
    title = models.CharField(max_length = 100, default = "FuliangMart")

    image = models.ImageField(upload_to="user_directroy_path", default= "vendor.jpg")
    cover_image = models.ImageField(upload_to="user_directroy_path", default= "vendor.jpg")
    # description = models.TextField(null=True, blank=True, default = "I am a Honest vendor.")
    description = RichTextUploadingField(null=True, blank=True, default = "I am a Honest vendor.")

    address = models.CharField(max_length = 100, default = "123, Mirpur-11, Dhaka.")
    contact = models.CharField(max_length = 100, default = "+880 0000000000")


    chat_resp_time = models.CharField(max_length = 100, default = "100")
    shiping_on_time = models.CharField(max_length = 100, default = "100")

    authentic_rating = models.CharField(max_length = 100, default = "100")
    days_return = models.CharField(max_length = 100, default = "100")

    warrenty_period = models.CharField(max_length = 100, default = "100")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    date = models.DateTimeField(auto_now_add = True, null=True, blank=True)
 
    class Meta:
        verbose_name_plural = "vendors"

    def vendor_image(self):
        return mark_safe('<img src="%s" width = "50" height = "50" />' % (self.image.url))
        
    def __str__(self):
        return self.title   

class Product(models.Model):
    pid = ShortUUIDField(unique = True, length = 10, max_length = 30, alphabet = "abcdefgh12345")
    title = models.CharField(max_length = 100, default = "LifeBook S Series")

    image = models.ImageField(upload_to="user_directroy_path", default= "product.jpg")
    # description = models.TextField(null=True, blank=True, default = "this a very good product")
    description = RichTextUploadingField(null=True, blank=True, default = "this a very good product")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True, related_name = "product")

    price = models.DecimalField(max_digits=12, decimal_places=2, default = "1.00")
    old_price = models.DecimalField(max_digits=12, decimal_places=2, default = "2.00")

    type = models.CharField(max_length=100, default = "Organic", null=True, blank=True)
    stock_count = models.CharField(max_length=100, default = "10", null=True, blank=True)

    valid = models.CharField(max_length=100, default = "100 Days", null=True, blank=True)
    mfd = models.DateTimeField(auto_now_add=False, null=True, blank=True)

    # specifications= models.TextField(null=True, blank= True)
    specifications= RichTextUploadingField(null=True, blank= True)

    # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True)
    tags = TaggableManager(blank=True)

    product_status = models.CharField(choices = STATUS, max_length = 10, default = "in_review")
    status = models.BooleanField(default=True)

    stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)

    digital = models.BooleanField(default=False)
    sku = ShortUUIDField(unique=True, length = 4, max_length = 10, prefix="sku", alphabet = "1234567890")
    
    date = models.DateField(auto_now_add = True)
    updated = models.DateField(null = True, blank = True)
   
    class Meta:
        verbose_name_plural = "products"

    def product_image(self):
        return mark_safe('<img src="%s" width = "50" height = "50" />' % (self.image.url))
        
    def __str__(self):
        return self.title
    
    def get_precentage(self):
        new_price = ((self.old_price - self.price) / self.old_price) * 100
        return new_price
    
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images",default="product.jpg")
    product = models.ForeignKey(Product,related_name = "p_images", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name_plural = "Product Images"

###################################### Cart, Order, OrderItems  ###########################

class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=12, decimal_places=2, default = "1.99")

    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)

    product_status = models.CharField(choices = STATUS_CHOICE, max_length = 10, default = "Processing")
    sku = ShortUUIDField(null=True, blank=True, length=5, prefix = "SKU", max_length=20, alphabet="1234567890")
    oid = ShortUUIDField(null=True, blank=True, length=5, prefix = "OID", max_length=20, alphabet="1234567890")

    # billing details fields
    full_name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    house_address = models.CharField(max_length=255, null=True, blank=True)
    road_name = models.CharField(max_length=255, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    saved = models.DecimalField(max_digits=12, decimal_places=2, default = "0.00")
    shipping_method = models.CharField(max_length=100, null=True, blank=True)

    traking_id = models.CharField(max_length=100, null=True, blank=True)
    traking_website_address = models.CharField(max_length=100, null=True, blank=True)

    stripe_payment_intent = models.CharField(max_length=100, null=True, blank=True)
    coupons = models.ManyToManyField("martApp.Coupon", blank=True)
    
    def __str__(self):
        return f"Order #{self.id} by {self.user.username}"

    class Meta:
        verbose_name_plural = "Cart Order"

class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length = 200)
    product_status = models.CharField(max_length = 200)

    items = models.CharField(max_length = 200)
    image = models.CharField(max_length = 200)

    qty = models.IntegerField(default = 0)
    price = models.DecimalField(max_digits=12, decimal_places=2, default = "1.99")
   
    total = models.DecimalField(max_digits=12, decimal_places=2, default = "1.99")
    
    class Meta:
        verbose_name_plural = "Cart Order Items"

    def order_img(self):
        return mark_safe('<img src="/media/%s" width = "50" height = "50" />' % (self.image.url))
    

###################################### product review, wishlists, address  ###########################

class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name = "reviews")

    review = models.TextField()
    rating = models.IntegerField(choices=RATINGS, default=None)

    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Reviews"
   
    def __str__(self):
        return self.product.title
    
    def get_rating(self):
        return self.rating
    

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)

    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Wishlists"
   
    def __str__(self):
        return self.product.title


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    mobail = models.CharField(max_length = 100, null=True)
    address= models.CharField(max_length = 100, null=True)

    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address"    


class Coupon(models.Model):
    code = models.CharField(max_length = 50)
    discount = models.IntegerField(default = 1)
    active = models.BooleanField(default = True)

    def __str__(self):
        return self.code

FuliangMart/useradmin/models.py
from django.db import models

# Create your models here.

FuliangMart/useradmin/forms.py
from martApp.models import Product
from django import forms


class AddProductForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Enter Product Title", "class":"form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Product Description", "class":"form-control"}))
    price = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "Sale Price", "class":"form-control"}))
    old_price = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "Old Price", "class":"form-control"}))
    type = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Type of product e.g organic cream", "class":"form-control"}))
    stock_count = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "How many are in stock?", "class":"form-control"}))
    life = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "How long would this product live?", "class":"form-control"}))
    mfd = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'placeholder': "e.g: 22-11-02", "class":"form-control"}))
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Tags", "class":"form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}))

    class Meta:
        model = Product
        fields = [
            "title",
            "image",
            "description",
            "price",
            "old_price",
            "specifications",
            "type",
            "stock_count",
            "mfd",
            "tags",
            "digital",
            "category",
        ]

FuliangMart/templates/useradmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>FuliangMart Dashboard</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta property="og:title" content="" />
    <meta property="og:type" content="" />
    <meta property="og:url" content="" />
    <meta property="og:image" content="" />
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="assets2/imgs/theme/favicon.svg" />
    <!-- Template CSS -->
    <link href="{% static 'assets2/css/main.css' %}" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>

<body>
    <div class="screen-overlay"></div>
    <aside class="navbar-aside" id="offcanvas_aside">
        <div class="aside-top">
            <a href="index.html" class="brand-wrap">
                    <img src="{% static 'assets2/imgs/theme/logo.svg' %}" class="logo" alt="Nest Dashboard" />
                </a>
            <div>
                <button class="btn btn-icon btn-aside-minimize"><i class="text-muted material-icons md-menu_open"></i></button>
            </div>
        </div>
        <nav>
            <ul class="menu-aside">
                <li class="menu-item {% if '/useradmin/dashboard/' in request.path %} active{% endif %}">
                    <a class="menu-link" href="{% url 'useradmin:dashboard' %}">
                            <i class="icon material-icons md-home"></i>
                            <span class="text">Dashboard</span>
                        </a>
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="{% url 'useradmin:products' %}">
                        <i class="icon material-icons md-shopping_bag"></i>

                            <span class="text">Products</span>
                        </a>
                    
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="{% url 'useradmin:orders' %}">
                            <i class="icon material-icons md-shopping_cart"></i>
                            <span class="text">Orders</span>
                        </a>
                    <!-- <div class="submenu">
                        <a href="page-orders-1.html">Order list 1</a>
                        <a href="page-orders-2.html">Order list 2</a>
                        <a href="page-orders-detail.html">Order detail</a>
                    </div> -->
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="{%if vendor %}{% url 'useradmin:shop_page' vendor.vid %}{% else %} # {% endif %}">
                            <i class="icon material-icons md-store"></i>
                            <span class="text">Sellers</span>
                        </a>
                    <!-- <div class="submenu">
                        <a href="page-sellers-cards.html">Sellers cards</a>
                        <a href="page-sellers-list.html">Sellers list</a>
                        <a href="page-seller-detail.html">Seller profile</a>
                    </div> -->
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="">
                            <i class="icon material-icons md-add_box"></i>
                            <span class="text">Add product</span>
                        </a>
                    
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="page-transactions-1.html">
                            <i class="icon material-icons md-monetization_on"></i>
                            <span class="text">Transactions</span>
                        </a>
                    <!-- <div class="submenu">
                        <a href="page-transactions-1.html">Transaction 1</a>
                        <a href="page-transactions-2.html">Transaction 2</a>
                    </div> -->
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="#">
                            <i class="icon material-icons md-person"></i>
                            <span class="text">Account</span>
                        </a>
                    <div class="submenu">
                        <a href="page-account-login.html">User login</a>
                        <a href="page-account-register.html">User registration</a>
                        <a href="page-error-404.html">Error 404</a>
                    </div>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'useradmin:reviews' %}">
                            <i class="icon material-icons md-comment"></i>
                            <span class="text">Reviews</span>
                        </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="page-brands.html"> <i class="icon material-icons md-stars"></i> <span class="text">Brands</span> </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" disabled href="#">
                            <i class="icon material-icons md-pie_chart"></i>
                            <span class="text">Statistics</span>
                        </a>
                </li>
            </ul>
            <hr />
            <ul class="menu-aside">
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="{% url 'useradmin:settings' %}">
                            <i class="icon material-icons md-settings"></i>
                            <span class="text">Settings</span>
                        </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'useradmin:change_password' %}">
                            <i class="icon material-icons md-local_offer"></i>
                            <span class="text"> Change password </span>
                        </a>
                </li>
            </ul>
            <br />
            <br />
        </nav>
    </aside>
    <main class="main-wrap">
        <header class="main-header navbar">
            <div class="col-search">
                <form class="searchform">
                    <div class="input-group">
                        <input list="search_terms" type="text" class="form-control" placeholder="Search term" />
                        <button class="btn btn-light bg" type="button"><i class="material-icons md-search"></i></button>
                    </div>
                    <datalist id="search_terms">
                            <option value="Products"></option>
                            <option value="New orders"></option>
                            <option value="Apple iphone"></option>
                            <option value="Ahmed Hassan"></option>
                        </datalist>
                </form>
            </div>
            <div class="col-nav">
                <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"><i class="material-icons md-apps"></i></button>
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link btn-icon" href="#">
                                <i class="material-icons md-notifications animation-shake"></i>
                                <span class="badge rounded-pill">3</span>
                            </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn-icon darkmode" href="#"> <i class="material-icons md-nights_stay"></i> </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
                    </li>
                    <li class="dropdown nav-item">
                        <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownLanguage" aria-expanded="false"><i class="material-icons md-public"></i></a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownLanguage">
                            <a class="dropdown-item text-brand" href="#"><img src="{% static 'assets2/imgs/theme/flag-us.png' %}" alt="English" />English</a>
                            <a class="dropdown-item" href="#"><img src="{% static 'assets2/imgs/theme/flag-fr.png' %}" alt="Français" />বাংলা</a>
                            <a class="dropdown-item" href="#"><img src="{% static 'assets2/imgs/theme/flag-jp.png' %}" alt="Français" />日本語</a>
                            <a class="dropdown-item" href="#"><img src="{% static 'assets2/imgs/theme/flag-cn.png' %}" alt="Français" />中国人</a>
                        </div>
                    </li>
                    <li class="dropdown nav-item">
                        <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> <img class="img-xs rounded-circle" src="{% static 'assets2/imgs/people/avatar-2.png' %}" alt="User" /></a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                            <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                            <a class="dropdown-item" href="#"><i class="material-icons md-settings"></i>Account Settings</a>
                            <a class="dropdown-item" href="#"><i class="material-icons md-account_balance_wallet"></i>Wallet</a>
                            <a class="dropdown-item" href="#"><i class="material-icons md-receipt"></i>Billing</a>
                            <a class="dropdown-item" href="#"><i class="material-icons md-help_outline"></i>Help center</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item text-danger" href="#"><i class="material-icons md-exit_to_app"></i>Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </header>
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
        {% endif %}
        <script>
            setTimeout (() => {
                $(".alert").alert("close");
            }, 3000)
        </script>

        {% block content %}
          
        {% endblock content %}


        <!-- content-main end// -->
        <footer class="main-footer font-xs">
            <div class="row pb-30 pt-15">
                <div class="col-sm-6">
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    &copy; FuliangMart - Ecommerce Co.
                </div>
                <div class="col-sm-6">
                    <div class="text-sm-end">All rights reserved</div>
                </div>
            </div>
        </footer>
    </main>
    <script src="{% static 'assets2/js/vendors/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets2/js/vendors/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets2/js/vendors/select2.min.js' %}"></script>
    <script src="{% static 'assets2/js/vendors/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'assets2/js/vendors/jquery.fullscreen.min.js' %}"></script>
    <script src="{% static 'assets2/js/vendors/chart.js' %}"></script>
    <!-- Main Script -->
    <script src="{% static 'assets2/js/main.js?v=1.1' %}" type="text/javascript"></script>
    <!-- <script src="{% static 'assets2/js/custom-chart.js' %}" type="text/javascript"></script> -->
</body>

</html>

FuliangMart/templates/useradmin/change_password.html
{% extends 'useradmin/base.html' %}
{% load static %}

{% block content %}
<section class="content-main">
    <div class="content-header">
        <h2 class="content-title">Change Password</h2>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row gx-5">
                <div class="col-lg-12">
                    <section class="content-body p-xl-4">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="row gx-3">
                                        <div class="col-12 mb-3">
                                            <label class="form-label">Old Password</label>
                                            <input class="form-control" name="old_password" value="" type="password" placeholder="***********" />
                                        </div>
                                        <div class="col-12 mb-3">
                                            <label class="form-label">New Password</label>
                                            <input class="form-control" name="new_password" value="" type="password" placeholder="***********" />
                                        </div>
                                        <div class="col-lg-12 mb-3">
                                            <label class="form-label">Confirm Password</label>
                                            <input class="form-control" name="confirm_new_password" value="" type="password" placeholder="***********" />
                                        </div>
                                    </div>
                                </div>
                                <aside class="col-lg-4">
                                    <figure class="text-lg-center">
                                        {% if request.user.profile.image %}
                                        <img class="img-lg mb-3 img-avatar" src="{{request.user.profile.image.url}}" alt="User Photo" />
                                        {% else %}
                                        <img class="img-lg mb-3 img-avatar" src="https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2281862025.jpg" alt="User Photo" />
                                        {% endif %}
                                    </figure>
                                </aside>
                            </div>
                            <br />
                            <button class="btn btn-primary" type="submit">Save New Password <i class="fas fa-check-circle mt-1 ms-2"></i></button>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

FuliangMart/templates/useradmin/payment-success.html
<div class="row justify-content-center pt-lg-4 text-center" style="margin-bottom: 200px; margin-top: 100px;">
    <div class="col-lg-5 col-md-7 col-sm-9">
        <h1 class="display-404 py-lg-3">Payment Completed</h1>
        <h2 class="h3 mb-4">Your order has been successfully placed. Order Id #2358934</h2>
        <p class="fs-md mb-4">
        <a href="#">Contact us</a> if you have any issue or question
        </p>
    </div>
</div>