FuliangMart/FuliangMart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("martApp.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    # this is for ckeditor app for customize web text(like product: title, descriptions etc) editor
    path("ckeditor/", include("ckeditor_uploader.urls"))

    # paypal integrations
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

FuliangMart/martApp/urls.py
from django.urls import path, include
from martApp.views import index, checkout, ajax_contact, contact, remove_wishlist, add_to_wishlist, wishlist_view, make_address_default, order_success, order_detail, customer_dashboard,  update_cart, delete_item_from_cart, cart_view, add_to_cart, search_view, filter_product, product_list_view, ajax_add_review, tag_list, categories_list, category_product_list_view, vendor_list_view, vendor_detail_view, product_detail_view
from martApp import views

app_name = "martApp"

urlpatterns = [
    path("", index, name="index"),
    path("products/", product_list_view, name="product_list"),

    path("product/<pid>/", product_detail_view, name="product_detail"),
    path("category/", categories_list, name="categories"),

    path("category/<cid>/", category_product_list_view, name="category-product-list"),
    path("vendor/", vendor_list_view, name="vendor_list"),
    
    path("vendors/<vid>/", vendor_detail_view, name="vendor_detail"),
    path("tag/<slug:tag_slug>/", tag_list, name="tag_list"),
    # add review
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),
    
    path("search/", search_view, name="search"),
    # product filter
    path("filter-products/", filter_product, name="filter-product"),
    # add to cart link
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart"),

    path("update-cart/", update_cart, name="update-cart"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),


    path("wishlist/", wishlist_view, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),

    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),

    # path("checkout/<str:oid>/", checkout, name="checkout"),
    path("checkout/<oid>", checkout, name="checkout"),
    

    path('order-success/', order_success, name="order_success"),
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),

    path("dashboard/", customer_dashboard, name="dashboard"),
    path("contact/", contact, name="contact"),

    path("ajax-contact-form/", ajax_contact, name="ajax-contact-form"),

    # making address default
    path('make-default-address/', make_address_default, name="make-address-default"),
    
    
    # new path
    path('save-checkout-info/', views.save_checkout_info, name="save_checkout_info"),
    
    path('privacy_policy/', views.privacy_policy, name="privacy_policy"),
    path('purchase_guide/', views.purchase_guide, name="purchase_guide"),
    path('terms_of_service/', views.terms_of_service, name="terms_of_service"),
    path('about_us/', views.about_us, name="about_us"),
    
]

FuliangMart/templates/core/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main" id="cart-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="/" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                    </div>
                </div>
            </div>
            <form action="{% url 'martApp:save_checkout_info' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-8">
                        <div class="table-responsive shopping-summery">
                            <table class="table table-wishlist">
                                <thead>
                                    <tr class="main-heading">
                                        
                                        <th scope="col">Product</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Unit Price</th>
                                        <th scope="col" class="text-center">Quantity</th>
                                        <th scope="col">Subtotal</th>
                                        <th scope="col" class="">Refresh</th>
                                        <th scope="col" class="end">Remove</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product_id, item in cart_data.items %}
                                    <tr class="pt-30">
                                        <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                        <td class="product-des product-name">
                                            <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'martApp:product_detail' item.pid %}">{{ item.title }}</a></h6>
                                        
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h4 class="text-body">${{item.price|floatformat:2}}</h4>
                                        </td>
                                        <td class="text-center detail-info" data-title="Stock">
                                            <div class="mr-15">
                                                <input type="number" placeholder="Qty" class="w-25 product-qty-{{ product_id }}"  name="" value="{{ item.qty }}" id="">
                                            </div>
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h4 class="text-brand">${% widthratio item.price 1 item.qty %} </h4>
                                        </td>
                                        <td class="action text-center" data-title="Remove"><a style="border: none; background: none;"  class="text-body update-product" data-product="{{ product_id }}"><i class="fi-rs-refresh"></i></a></td>
                                        <td class="action text-center" data-title="Remove"><a style="border: none; background: none;"  class="text-body delete-product" data-product="{{ product_id }}"><i class="fi-rs-trash"></i></a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                            <div class="row mt-4">
                                <h4 class="mb-30">Bio Data</h4>
                                <div class="row">
                                    <div class="form-group col-lg-12">
                                        <label for="">Full Name</label>
                                        <input type="text" required="" name="full_name" value="{{request.user.username|title}}" placeholder="Full Name">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Email</label>
                                        <input type="text" required="" name="email"  placeholder="mobile *" value="{{request.user.email}}">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Mobile</label>
                                        <input type="text" name="phone" value="{{request.user.profile.phone}}" required="" placeholder="Phone *">
                                    </div>
                                </div>
                                <h4 class="mb-30">Shipping Details</h4>
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label for="">Address</label>
                                        <input type="text" name="house" value="{{ active_address.address }}" placeholder="House No.">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Road</label>
                                        <input type="text" name="road"  placeholder="Road *" value="">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">City</label>
                                        <input type="text" name="city" value="" placeholder="city *">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="border p-md-4 cart-totals ml-30">
                            <div class="table-responsive">
                                <div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Tax</p>
                                        <p>$0</p>
                                    </div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Shipping</p>
                                        <p>$0</p>
                                    </div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Discount</p>
                                        <p>$0</p>
                                    </div>
                                    
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Total</p>
                                        <p>${{cart_total_amount}}</p>
                                    </div>
                                </div>
                            </div>
                            {% if totalcartitems %}
                                <button type="submit" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></button>
                            {% endif %}                    
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

FuliangMart/templates/core/category-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main">
        <div class="page-header mt-30 mb-75">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">Categories</h1>
                            <div class="breadcrumb">
                                <a href="/" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Category
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="page-content mb-50">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <div class="shop-product-fillter mb-50 pr-30">
                            <div class="totall-product">
                                <h2>
                                    <img class="w-36px mr-10" src="assets/imgs/theme/icons/category-1.svg" alt="" />
                                    <!------- total category ------>
                                    {{categories.count}} Categories 
                                </h2>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span>Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Featured</a></li>
                                            <li><a href="#">Newest</a></li>
                                            <li><a href="#">Most comments</a></li>
                                            <li><a href="#">Release Date</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="hello">

                        </div>
                        <div class="loop-grid pr-30">
                            <div class="row">
                                {% for c in categories %}
                                <article class="col-xl-4 col-lg-6 col-md-6 text-center hover-up mb-30 animated">
                                    <div class="post-thumb">
                                        <a href="{% url 'martApp:category-product-list' c.cid %}">
                                            <img style="height: 300px; width: 300px; object-fit: cover;" class="border-radius-15" src="{{c.image.url}}" alt="" />
                                        </a>
                                        <div class="entry-meta">
                                            <a class="entry-meta meta-2" href="#"><i class="fi-rs-heart"></i></a>
                                        </div>
                                    </div>
                                    <div class="entry-content-2">
                                        <h4 class="post-title mb-15">
                                            <a href="{% url 'martApp:category-product-list' c.cid %}">{{ c.title }}</a>
                                        </h4>
                                        <div class="entry-meta font-xs color-grey mt-10 pb-10">
                                            <div>
                                                <span class="hit-count mr-10">{{c.category.count}} Product{{c.category.count|pluralize}}</span>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-start">
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                                    </li>
                                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                    <li class="page-item"><a class="page-link" href="#">6</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div> -->
                    </div>
                    <div class="col-lg-3 primary-sidebar sticky-sidebar">
                        <div class="widget-area">
                            <div class="sidebar-widget-2 widget_search mb-50">
                                <div class="search-form">
                                    <form action="#">
                                        <input type="text" placeholder="Search…" />
                                        <button type="submit"><i class="fi-rs-search"></i></button>
                                    </form>
                                </div>
                            </div>
                            <div class="sidebar-widget widget-category-2 mb-50">
                                <h5 class="section-title style-1 mb-30">Category</h5>
                                <ul>
                                    {% for c in categories %}
                                    <li>
                                        <a href=""> <img src="{{c.image.url}}" alt="" />{{c.title}}</a><span class="count">{{c.category.count}}</span>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>


                            <div class="banner-img wow fadeIn mb-50 animated d-lg-block d-none">
                                <img src="assets/imgs/banner/banner-11.png" alt="" />
                                <div class="banner-text">
                                    <span>Oganic</span>
                                    <h4>
                                        Save 17% <br />
                                        on <span class="text-brand">Oganic</span><br />
                                        Juice
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}

FuliangMart/templates/core/category-product-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main">
        <div class="page-header mt-30 mb-50">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">{{category.title}}</h1>
                            <div class="breadcrumb">
                                <a href="{% url 'martApp:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Shop <span></span> {{category.title}}
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="container mb-30">
            <div class="row">
                <div class="col-12">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We found <strong class="text-brand">{{product.count}}</strong> item{{product.count|pluralize}} for you!</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Featured</a></li>
                                        <li><a href="#">Price: Low to High</a></li>
                                        <li><a href="#">Price: High to Low</a></li>
                                        <li><a href="#">Release Date</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row product-grid">
                        {% for p in product %}
                        <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                            <div class="product-cart-wrap mb-30">
                                <div class="product-img-action-wrap">
                                    <div class="product-img product-img-zoom">
                                        <a href="{% url 'martApp:product_detail' p.pid%}">
                                            <img class="default-img" src="{{ p.image.url }}" alt="" style="height: 280px; width: 280px; object-fit: cover;"   />
                                            <img class="hover-img" src="{{ p.image.url }}" alt=""  style="height: 280px; width: 280px; object-fit: cover;"  />

                                        </a>
                                    </div>
                                    <div class="product-action-1">
                                        <a aria-label="Add To Wishlist"  class="action-btn add-to-wishlist" data-product-item="{{p.id}}"><i class="fi-rs-heart"></i></a>
                                        <!-- <a aria-label="Compare" class="action-btn" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a> -->
                                        <a href="{% url 'martApp:product_detail' p.pid %}" class="action-btn"><i class="fi-rs-eye"></i></a>
                                    </div>
                                    <div class="product-badges product-badges-position product-badges-mrg">
                                        <span class="hot">-{{p.get_precentage|floatformat:0}}%</span>
                                    </div>
                                </div>
                                <div class="product-content-wrap">
                                    <div class="product-category">
                                        <a href="">{{ p.category.title }}</a>
                                    </div>
                                    <h2><a href="{% url 'martApp:product_detail' p.pid %}">{{ p.title }}</a></h2>
                                    <div class="product-rate-cover">
                                        <i class="fas fa-star text-warning"></i>
                                        <span class="font-small ml-5 text-muted"> ({{ p.reviews.all.count }})</span>

                                    </div>
                                    <div>
                                        <span class="font-small text-muted">By <a href="/">{{p.vendor.title}}</a></span>
                                    </div>
                                    <div class="product-card-bottom">
                                        <div class="product-price">
                                            <span>$</span> <span class="current-product-price-{{ p.id }}">{{p.price}}</span>
                                            <span class="old-price">${{p.old_price}}</span>
                                        </div>
                                        <div class="add-cart">
                                            <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ p.id }}">
                                            <input type="hidden" class="product-pid-{{ p.id }}" value="{{ p.pid }}">
                                            <input type="hidden" class="product-image-{{ p.id }}" value="{{ p.image.url }}">
                                            <input type="hidden" class="product-id-{{ p.id }}" value="{{ p.id }}">
                                            <input type="hidden" class="product-title-{{ p.id }}" value="{{ p.title }}">
                                            <div class="d-flex">
                                                <button class="add add-to-cart-btn" data-index="{{ p.id }}" style="border: none;" id="add-to-cart-btn"><i class="fi-rs-shopping-cart mr-5"></i>Add</button>
                                                <button style="border: none; background: none;" class="add-to-wishlist" data-product-item="{{p.id}}"><i class="fi-rs-heart" style="fill: aqua;"></i></button>
                                            </div>
                                            <!-- <button class="add add-to-cart-btn" data-index="{{ p.id }}" style="border: none;" id="add-to-cart-btn"><i class="fi-rs-shopping-cart mr-5"></i>Add</button> -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!--product grid-->
                    <!-- <div class="pagination-area mt-20 mb-20">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-start">
                                <li class="page-item">
                                    <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                <li class="page-item"><a class="page-link" href="#">6</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                                </li>
                            </ul>
                        </nav>
                    </div> -->
                </div>
            </div>
        </div>
    </main>
   
{% endblock content %}